name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Run E2E with Maven
        run: mvn --batch-mode --update-snapshots -Pe2e verify

      - name: Prepare staging dir
        run: mkdir staging && cp runtime/target/*.jar staging/

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Package
          path: staging

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Package
          path: staging

      - name: Release
        run: gh release upload ${{ github.ref_name }} staging/*.jar
        env:
          GH_TOKEN: ${{ github.token }}
